
import React,{useMemo,useState}from'react';import{createRoot}from'react-dom/client';import questions from'./questions.json';import'./style.css';
const LS='tarih_stats_v1';
function loadStats(){try{return JSON.parse(localStorage.getItem(LS)||'{}')}catch{return{}}}
function saveStats(s){localStorage.setItem(LS,JSON.stringify(s))}
function shuffle(a){let x=[...a];for(let i=x.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x}
function fillQuestion(q,revealed){let parts=String(q.question).split(/_{5,}/g); if(parts.length===1)return q.question; let out=[]; for(let i=0;i<parts.length;i++){out.push(<React.Fragment key={'p'+i}>{parts[i]}</React.Fragment>); if(i<parts.length-1){out.push(<span key={'b'+i} className={revealed?'answer':'blank'}>{revealed?(q.answers?.[i]||'???'):'____________'}</span>)}} return out}
function App(){const[page,setPage]=useState('menu');const[stats,setStats]=useState(loadStats);const[session,setSession]=useState([]);const[i,setI]=useState(0);const[revealed,setRevealed]=useState(false);const[title,setTitle]=useState('');const[topic,setTopic]=useState('');const topics=useMemo(()=>[...new Set(questions.map(q=>q.topic))].sort(),[]);function start(mode,t){let s=[];let ttl='';if(mode==='topic'){s=questions.filter(q=>q.topic===t);ttl=t}else if(mode==='wrong'){let ids=new Set(Object.entries(stats).filter(([,r])=>r.result==='wrong').map(([id])=>id));s=questions.filter(q=>ids.has(q.id));ttl='Yanlış Sorular Tekrarı';if(!s.length){alert('Şu an tekrar edilecek yanlış soru yok.');return}}else{s=questions;ttl='Genel Karışık Tekrar'}setSession(shuffle(s));setI(0);setRevealed(false);setTitle(ttl);setPage('study')}function record(ok){let q=session[i];let ns={...stats,[q.id]:{topic:q.topic,subtopic:q.subtopic||'',result:ok?'correct':'wrong',time:new Date().toISOString()}};setStats(ns);saveStats(ns);if(i+1>=session.length){alert('Oturum bitti. Bu oturumdaki tüm sorular tamamlandı.');setPage('menu')}else{setI(i+1);setRevealed(false)}}function rows(){let map={};topics.forEach(t=>map[t]={topic:t,total:0,seen:0,correct:0,wrong:0,rate:0});questions.forEach(q=>map[q.topic].total++);Object.values(stats).forEach(r=>{if(map[r.topic]&&(r.result==='correct'||r.result==='wrong')){map[r.topic].seen++; if(r.result==='correct')map[r.topic].correct++; else map[r.topic].wrong++}});Object.values(map).forEach(r=>{let n=r.correct+r.wrong;r.rate=n?Math.round(r.correct/n*1000)/10:0});return Object.values(map).sort((a,b)=>(a.wrong===0)-(b.wrong===0)||b.wrong-a.wrong||a.rate-b.rate)}function reset(){if(confirm('Tüm doğru/yanlış kayıtları silinsin mi?')){setStats({});saveStats({})}}const q=session[i];if(page==='menu')return <main className="page"><section className="card"><h1 className="title">Tarih Çalışma</h1><p className="subtitle">{questions.length} soru • {topics.length} konu • karışık tekrar sistemi</p><button className="btn" onClick={()=>setPage('topic')}>Konu Bazlı Çalış</button><button className="btn" onClick={()=>start('all')}>Tüm Konuları Karışık Tekrar Et</button><button className="btn bad" onClick={()=>start('wrong')}>Yanlış Yaptığım Soruları Çalış</button><button className="btn ghost" onClick={()=>setPage('stats')}>İstatistikler ve Zayıf Konular</button><p className="note">Kural: Her oturumda sorular rastgele karıştırılır ve aynı soru ikinci kez çıkmaz.</p></section></main>;
if(page==='topic')return <main className="page"><section className="card"><h1 className="title">Konu Seç</h1><p className="subtitle">Seçilen konudaki tüm sorular karışık sırayla gelir.</p><select className="select" value={topic} onChange={e=>setTopic(e.target.value)}><option value="">Konu seç</option>{topics.map(t=><option key={t} value={t}>{t} ({questions.filter(q=>q.topic===t).length} soru)</option>)}</select><button className="btn" disabled={!topic} onClick={()=>start('topic',topic)}>Bu Konuyu Çalış</button><button className="btn ghost" onClick={()=>setPage('menu')}>Ana Menü</button></section></main>;
if(page==='stats')return <main className="page"><section className="card"><h1 className="title">İstatistikler</h1><p className="subtitle">Tek seferlik tutulur: Her soru için yalnızca son sonuç sayılır. Yanlışlar doğru yapılınca listeden düşer.</p><div className="table-wrap"><table><thead><tr><th>Konu</th><th>Soru</th><th>Çalışılan</th><th>Doğru</th><th>Yanlışta Duran</th><th>Başarı %</th></tr></thead><tbody>{rows().map(r=><tr key={r.topic}><td>{r.topic}</td><td>{r.total}</td><td>{r.seen}</td><td>{r.correct}</td><td>{r.wrong}</td><td>{r.rate}</td></tr>)}</tbody></table></div><div className="row"><button className="btn ghost" onClick={()=>setPage('menu')}>Ana Menü</button><button className="btn bad" onClick={()=>start('wrong')}>Yanlış Soruları Çalış</button><button className="btn ghost" onClick={reset}>İstatistikleri Sıfırla</button></div></section></main>;
return <main className="page"><section className="card"><div className="topbar"><h1 className="title">{title}</h1><div className="counter">{i+1} / {session.length}</div></div><div className="progress"><div style={{width:`${(i/session.length)*100}%`}}/></div><section className="card study-card"><p className="subtitle">{q?.subtopic||''}</p><div className="question">{q&&fillQuestion(q,revealed)}</div></section><div className="row">{!revealed?<button className="btn" onClick={()=>setRevealed(true)}>Cevabı Yerine Koy</button>:<><button className="btn good" onClick={()=>record(true)}>Doğru Yaptım</button><button className="btn bad" onClick={()=>record(false)}>Yanlış Yaptım</button></>}<button className="btn ghost" onClick={()=>setPage('menu')}>Ana Menü</button></div></section></main>}
createRoot(document.getElementById('root')).render(<App/>);
